spring:
  application:
    name: currencyconverter

  data:
    mongodb:
      uri: mongodb://localhost:27018/currency_db

server:
  port: 8082

exchange:
  api:
    key: 891476adbf6164142f50cb99
    url: https://v6.exchangerate-api.com/v6  
